#.libPaths('D:/Program Files (x86)/R-3.5.2/library')
library(parallel)
library(biomaRt)
library(shiny)
library(plyr)
library(ggplot2)
library(jsonlite)
library(shinydashboard)
library(shinyWidgets)
library(DT)
library(ggthemr)
library(R.matlab)
library(tibble)
library(igraph)
library(scales)
library(rhandsontable)
library(PerformanceAnalytics)
#library(rJava)
library(linkcomm)
library(MCL)
library(visNetwork)
library(colourpicker)
#library(ProNet)
library(ggplotify)
library(survival)
library(survminer)
library(ComplexHeatmap)
library(circlize)
library(gprofiler2)
library(R.oo)
library(formattable)

# library(ggplotify)
#library(reshape2)
# library(plotly)
# library(d3heatmap)
# library(future)
# library(promises)

ggthemr('flat')
usedcolors=swatch()
source('www/R/customerUI.R')